title: Statistical Methods Course
description: Resources and materials for Statistical Methods
baseurl: ""
url: ""

# Build settings
markdown: kramdown
permalink: pretty

# Security headers for iframe embedding
webrick:
  headers:
    "X-Frame-Options": "ALLOW-FROM https://canvas.asu.edu"
    "Content-Security-Policy": "frame-ancestors 'self' https://canvas.asu.edu" 